// ============================================================
// Smart Memory — MemorySearch: orchestrates DB + VectorIndex + Embeddings
// ============================================================

import { homedir } from 'os';
import { join, basename } from 'path';
import { existsSync, mkdirSync, renameSync } from 'fs';
import { randomUUID, createHash } from 'crypto';
import { execFileSync } from 'child_process';

import { DatabaseManager } from './database.js';
import { VectorIndex } from './vector-index.js';
import { EmbeddingManager } from './embeddings.js';
import type {
  MemoryRecord,
  MemoryStoreInput,
  MemorySearchInput,
  MemoryQueryInput,
  MemorySearchResult,
  MemoryStats,
} from '../types.js';

// ── Storage paths ─────────────────────────────────────────────
// ~/.smart-memory/{namespace}/memory.db
//                            /index.bin

function getStorageDir(namespace: string): string {
  return join(homedir(), '.smart-memory', namespace);
}

function getProjectRoot(): string {
  try {
    return execFileSync('git', ['rev-parse', '--show-toplevel'], {
      encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
  } catch {
    return process.cwd();
  }
}

function defaultNamespace(): string {
  const root = getProjectRoot();
  const name = basename(root) || 'default';
  const hash = createHash('sha256').update(root).digest('hex').slice(0, 8);
  return `${name}-${hash}`;
}

/** Namespace generated by the old cwd-based logic (for migration) */
function legacyNamespace(): string {
  const cwd = process.cwd();
  const name = basename(cwd) || 'default';
  const hash = createHash('sha256').update(cwd).digest('hex').slice(0, 8);
  return `${name}-${hash}`;
}

// ── MemorySearch ──────────────────────────────────────────────

export class MemorySearch {
  private db: DatabaseManager;
  private index: VectorIndex;
  private embeddings: EmbeddingManager;
  private readonly namespace: string;
  private readonly storageDir: string;
  private initialized = false;

  constructor(namespace?: string) {
    this.namespace = namespace ?? defaultNamespace();
    this.storageDir = getStorageDir(this.namespace);
    this.db = new DatabaseManager(join(this.storageDir, 'memory.db'));
    this.index = new VectorIndex();
    this.embeddings = new EmbeddingManager();
  }

  async init(): Promise<void> {
    if (this.initialized) return;
    // Migrate from old cwd-based namespace to git-root-based namespace
    if (!existsSync(this.storageDir)) {
      const legacy = legacyNamespace();
      const legacyDir = getStorageDir(legacy);
      if (legacy !== this.namespace && existsSync(legacyDir)) {
        renameSync(legacyDir, this.storageDir);
        process.stderr.write(`[SmartMemory] Migrated namespace "${legacy}" → "${this.namespace}"\n`);
      } else {
        mkdirSync(this.storageDir, { recursive: true });
      }
    }
    await this.db.init();
    this.index.loadFrom(join(this.storageDir, 'index.bin'));
    this.initialized = true;
  }

  // ── Store ─────────────────────────────────────────────────

  async store(input: MemoryStoreInput): Promise<{ id: string; action: 'created' | 'updated' }> {
    await this.init();
    this.cleanExpired();

    const ns = input.namespace ?? this.namespace;
    const now = Date.now();
    const expiresAt = input.ttl_hours ? now + input.ttl_hours * 3_600_000 : null;
    const tags = JSON.stringify(input.tags ?? []);
    const metadata = JSON.stringify(input.metadata ?? {});
    const type = input.type ?? 'note';

    // Generate embedding
    const { vec, dims } = await this.embeddings.embed(input.content);
    // Use byteOffset+byteLength to handle TypedArray views into shared buffers
    // (Transformers.js returns views into pooled ArrayBuffers)
    const embedding = Buffer.from(vec.buffer, vec.byteOffset, vec.byteLength);

    // Check if key already exists in this namespace
    const existing = this.db.get<{ id: string }>(
      'SELECT id FROM memories WHERE key = ? AND namespace = ?',
      [input.key, ns],
    );

    if (existing) {
      // UPDATE
      this.db.run(
        `UPDATE memories SET
          content = ?, type = ?, tags = ?, embedding = ?, embedding_dims = ?,
          updated_at = ?, expires_at = ?, metadata = ?
         WHERE id = ?`,
        [input.content, type, tags, embedding, dims, now, expiresAt, metadata, existing.id],
      );
      this.index.set(existing.id, vec);
      this.persist();
      return { id: existing.id, action: 'updated' };
    } else {
      // INSERT
      const id = randomUUID();
      this.db.run(
        `INSERT INTO memories
          (id, key, content, namespace, type, tags, embedding, embedding_dims,
           created_at, updated_at, expires_at, metadata)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [id, input.key, input.content, ns, type, tags, embedding, dims,
         now, now, expiresAt, metadata],
      );
      this.index.set(id, vec);
      this.persist();
      return { id, action: 'created' };
    }
  }

  // ── Hybrid Search (vector + keyword) ─────────────────────

  async search(input: MemorySearchInput): Promise<MemorySearchResult[]> {
    await this.init();
    this.cleanExpired();

    const ns = input.namespace ?? this.namespace;
    const limit = input.limit ?? 10;
    const minSim = input.min_similarity ?? 0.3;
    const now = Date.now();
    const seenIds = new Set<string>();
    const candidates: MemorySearchResult[] = [];

    // ── 1. Vector search (semantic similarity) ──────────────
    const { vec } = await this.embeddings.embed(input.query);
    const vectorHits = this.index.search(vec, limit * 2, minSim);

    for (const hit of vectorHits) {
      const row = this.db.get<DbRow>(
        'SELECT * FROM memories WHERE id = ? AND namespace = ? AND (expires_at IS NULL OR expires_at > ?)',
        [hit.id, ns, now],
      );
      if (!row) continue;
      seenIds.add(row.id);
      const recency = recencyScore(now, row.updated_at as number);
      const blended = hit.similarity * 0.6 + recency * 0.2 + keywordScore(input.query, row.content, row.key) * 0.2;
      candidates.push(rowToResult(row, blended, hit.similarity));
    }

    // ── 2. Keyword search (exact match boost) ───────────────
    // Extract meaningful words (≥ 3 chars) for SQL LIKE matching.
    // This catches exact names, paths, and identifiers that vectors miss.
    const keywords = input.query
      .split(/\s+/)
      .map(w => w.replace(/[^\w.-]/g, ''))
      .filter(w => w.length >= 3);

    if (keywords.length > 0) {
      // Build OR conditions: content or key contains any keyword
      const likeClauses = keywords.map(() => '(content LIKE ? OR key LIKE ?)');
      const likeParams: unknown[] = [];
      for (const kw of keywords) {
        likeParams.push(`%${kw}%`, `%${kw}%`);
      }

      const keywordRows = this.db.all<DbRow>(
        `SELECT * FROM memories WHERE namespace = ? AND (expires_at IS NULL OR expires_at > ?)
         AND (${likeClauses.join(' OR ')})
         ORDER BY updated_at DESC LIMIT ?`,
        [ns, now, ...likeParams, limit * 2],
      );

      for (const row of keywordRows) {
        if (seenIds.has(row.id)) continue; // already scored via vector
        seenIds.add(row.id);
        const recency = recencyScore(now, row.updated_at as number);
        const kwScore = keywordScore(input.query, row.content, row.key);
        // No vector similarity → use keyword + recency only
        const blended = kwScore * 0.7 + recency * 0.3;
        // Only include if keyword relevance is meaningful
        if (blended >= minSim) {
          candidates.push(rowToResult(row, blended, 0));
        }
      }
    }

    // Re-sort by blended score and take top-k
    candidates.sort((a, b) => b.similarity - a.similarity);
    return candidates.slice(0, limit);
  }

  // ── SQL Query ─────────────────────────────────────────────

  async query(input: MemoryQueryInput): Promise<MemorySearchResult[]> {
    await this.init();
    this.cleanExpired();

    const conditions: string[] = ['(expires_at IS NULL OR expires_at > ?)'];
    const params: unknown[] = [Date.now()];

    const ns = input.namespace ?? this.namespace;
    conditions.push('namespace = ?');
    params.push(ns);

    if (input.type) {
      conditions.push('type = ?');
      params.push(input.type);
    }
    if (input.after) {
      conditions.push('created_at >= ?');
      params.push(new Date(input.after).getTime());
    }
    if (input.before) {
      conditions.push('created_at <= ?');
      params.push(new Date(input.before).getTime());
    }
    if (input.tags && input.tags.length > 0) {
      // JSON tag matching: each tag must appear in the JSON array.
      // Escape LIKE wildcards (% and _) and use ESCAPE clause to prevent
      // pattern injection — tags with % would otherwise match too broadly.
      for (const tag of input.tags) {
        const escaped = tag.replace(/\\/g, '\\\\').replace(/%/g, '\\%').replace(/_/g, '\\_');
        conditions.push(`tags LIKE ? ESCAPE '\\'`);
        params.push(`%"${escaped}"%`);
      }
    }

    const limit = input.limit ?? 50;
    const sql = `SELECT * FROM memories WHERE ${conditions.join(' AND ')} ORDER BY updated_at DESC LIMIT ?`;
    params.push(limit);

    const rows = this.db.all<DbRow>(sql, params);
    return rows.map(r => rowToResult(r, 1.0, 1.0));
  }

  // ── Stats ─────────────────────────────────────────────────

  async stats(): Promise<MemoryStats> {
    await this.init();

    const total = (this.db.get<{ n: number }>('SELECT COUNT(*) as n FROM memories') ?? { n: 0 }).n;
    const withEmbedding = (this.db.get<{ n: number }>(
      'SELECT COUNT(*) as n FROM memories WHERE embedding_dims > 0',
    ) ?? { n: 0 }).n;

    const nsRows = this.db.all<{ namespace: string; n: number }>(
      'SELECT namespace, COUNT(*) as n FROM memories GROUP BY namespace',
    );
    const typeRows = this.db.all<{ type: string; n: number }>(
      'SELECT type, COUNT(*) as n FROM memories GROUP BY type',
    );

    return {
      total,
      by_namespace: Object.fromEntries(nsRows.map(r => [r.namespace, r.n])),
      by_type: Object.fromEntries(typeRows.map(r => [r.type, r.n])),
      embedding_coverage: total > 0 ? withEmbedding / total : 0,
    };
  }

  // ── Internals ─────────────────────────────────────────────

  private cleanExpired(): void {
    const now = Date.now();
    // Collect IDs to remove from vector index
    const expired = this.db.all<{ id: string }>(
      'SELECT id FROM memories WHERE expires_at IS NOT NULL AND expires_at <= ?',
      [now],
    );
    for (const { id } of expired) this.index.delete(id);
    this.db.run('DELETE FROM memories WHERE expires_at IS NOT NULL AND expires_at <= ?', [now]);
  }

  private persist(): void {
    this.db.save();
    this.index.saveTo(join(this.storageDir, 'index.bin'));
  }

  // ── Delete ────────────────────────────────────────────────

  async delete(key: string, namespace?: string): Promise<{ deleted: boolean }> {
    await this.init();
    const ns = namespace ?? this.namespace;
    const existing = this.db.get<{ id: string }>(
      'SELECT id FROM memories WHERE key = ? AND namespace = ?',
      [key, ns],
    );
    if (!existing) return { deleted: false };
    this.index.delete(existing.id);
    this.db.run('DELETE FROM memories WHERE id = ?', [existing.id]);
    this.persist();
    return { deleted: true };
  }

  // ── Compact ──────────────────────────────────────────────

  async compact(namespace?: string): Promise<{
    embedded: number;
    expired_cleaned: number;
    total_after: number;
  }> {
    await this.init();

    // 1. Clean expired memories
    const expiredBefore = this.db.all<{ id: string }>(
      'SELECT id FROM memories WHERE expires_at IS NOT NULL AND expires_at <= ?',
      [Date.now()],
    );
    for (const { id } of expiredBefore) this.index.delete(id);
    this.db.run('DELETE FROM memories WHERE expires_at IS NOT NULL AND expires_at <= ?', [Date.now()]);

    // 2. Find memories without embeddings in this namespace
    const ns = namespace ?? this.namespace;
    const noEmbedding = this.db.all<{ id: string; content: string }>(
      'SELECT id, content FROM memories WHERE namespace = ? AND embedding_dims = 0',
      [ns],
    );

    // 3. Generate embeddings for each
    let embedded = 0;
    for (const row of noEmbedding) {
      try {
        const { vec, dims } = await this.embeddings.embed(row.content);
        const buf = Buffer.from(vec.buffer, vec.byteOffset, vec.byteLength);
        this.db.run(
          'UPDATE memories SET embedding = ?, embedding_dims = ? WHERE id = ?',
          [buf, dims, row.id],
        );
        this.index.set(row.id, vec);
        embedded++;
      } catch {
        // Skip failed embeddings — will retry on next compact
      }
    }

    if (embedded > 0) this.persist();

    const total = (this.db.get<{ n: number }>('SELECT COUNT(*) as n FROM memories WHERE namespace = ?', [ns]) ?? { n: 0 }).n;

    return {
      embedded,
      expired_cleaned: expiredBefore.length,
      total_after: total,
    };
  }

  close(): void {
    this.db.close();
  }
}

// ── DB row shape (raw from node:sqlite) ──────────────────────

interface DbRow {
  [key: string]: unknown;  // satisfies Row constraint from sql.js
  id: string;
  key: string;
  content: string;
  namespace: string;
  type: string;
  tags: string;           // JSON
  embedding_dims: number;
  created_at: number;
  updated_at: number;
  expires_at: number | null;
  metadata: string;       // JSON
}

function rowToResult(row: DbRow, similarity: number, rawSimilarity: number): MemorySearchResult {
  return {
    id: row.id,
    key: row.key,
    content: row.content,
    namespace: row.namespace,
    type: row.type,
    tags: JSON.parse(row.tags) as string[],
    similarity,
    raw_similarity: rawSimilarity,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}

// ── Scoring helpers ───────────────────────────────────────────

/** Exponential recency decay: 1.0 today → 0.37 at 30 days */
function recencyScore(now: number, updatedAt: number): number {
  const ageDays = (now - updatedAt) / 86_400_000;
  return Math.exp(-ageDays / 30);
}

/**
 * Keyword overlap score (0–1). Counts how many query tokens appear
 * in the content or key (case-insensitive). Rewards exact matches
 * in key higher than content matches.
 */
function keywordScore(query: string, content: string, key: string): number {
  const words = query.toLowerCase().split(/\s+/).filter(w => w.length >= 2);
  if (words.length === 0) return 0;

  const lowerContent = content.toLowerCase();
  const lowerKey = key.toLowerCase();
  let score = 0;

  for (const word of words) {
    if (lowerKey.includes(word)) {
      score += 1.0;        // exact match in key → full point
    } else if (lowerContent.includes(word)) {
      score += 0.6;        // match in content → partial point
    }
  }

  return Math.min(score / words.length, 1.0); // normalize to 0–1
}
