// ============================================================
// Smart Memory — MemorySearch: orchestrates DB + Embeddings
// ============================================================
// Hybrid search: BM25 (FTS5) + vector (cosine similarity)
// Score blending inspired by Monsthera's mergeResults pattern.
// ============================================================

import { homedir } from 'os';
import { join, basename, resolve, dirname } from 'path';
import { existsSync, mkdirSync, renameSync, unlinkSync } from 'fs';
import { randomUUID, createHash } from 'crypto';
import { execFileSync } from 'child_process';

import { DatabaseManager } from './database.js';
import { VectorIndex } from './vector-index.js';
import { EmbeddingManager } from './embeddings.js';
import type {
  MemoryRecord,
  MemoryStoreInput,
  MemorySearchInput,
  MemoryQueryInput,
  MemorySearchResult,
  MemoryStats,
  MemoryContextInput,
  MemoryContextResult,
  MemorySnapshotInput,
  MemorySnapshotResult,
  SearchConfig,
  SearchDebugInfo,
} from '../types.js';
import { DEFAULT_SEARCH_CONFIG } from '../types.js';

// ── Storage paths ─────────────────────────────────────────────
// ~/.smart-memory/{namespace}/memory.db

function getStorageDir(namespace: string): string {
  return join(homedir(), '.smart-memory', namespace);
}

function getProjectRoot(): string {
  try {
    const gitCommonDir = execFileSync('git', ['rev-parse', '--git-common-dir'], {
      encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    return dirname(resolve(gitCommonDir));
  } catch {
    return process.cwd();
  }
}

/** Namespace from the v1.1 --show-toplevel logic (for migration from worktrees) */
function showToplevelNamespace(): string {
  try {
    const toplevel = execFileSync('git', ['rev-parse', '--show-toplevel'], {
      encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    const name = basename(toplevel) || 'default';
    const hash = createHash('sha256').update(toplevel).digest('hex').slice(0, 8);
    return `${name}-${hash}`;
  } catch {
    return '';
  }
}

function defaultNamespace(): string {
  const root = getProjectRoot();
  const name = basename(root) || 'default';
  const hash = createHash('sha256').update(root).digest('hex').slice(0, 8);
  return `${name}-${hash}`;
}

/** Namespace generated by the old cwd-based logic (for migration) */
function legacyNamespace(): string {
  const cwd = process.cwd();
  const name = basename(cwd) || 'default';
  const hash = createHash('sha256').update(cwd).digest('hex').slice(0, 8);
  return `${name}-${hash}`;
}

// ── FTS5 Query Sanitization ──────────────────────────────────
// Inspired by Monsthera's sanitizeFts5Query with stop words,
// CamelCase expansion, and AND/OR threshold.

const STOP_WORDS = new Set([
  'a', 'an', 'the', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
  'of', 'with', 'by', 'from', 'is', 'it', 'as', 'be', 'was', 'are',
  'this', 'that', 'not', 'no', 'if', 'so', 'do', 'my', 'we', 'up',
]);

/** Split CamelCase into constituent words: "searchRouter" → ["search", "Router"] */
function splitCamelCase(value: string): string[] {
  return value.split(/(?<=[a-z])(?=[A-Z])|(?<=[A-Z])(?=[A-Z][a-z])/).filter(Boolean);
}

function isAllowedQueryToken(term: string): boolean {
  if (!term) return false;
  if (term.length < 2 && !/^[A-Z_]$/.test(term)) return false;
  return !STOP_WORDS.has(term.toLowerCase());
}

/** Expand a query term into CamelCase variants */
function expandQueryTerm(term: string): string[] {
  const variants = [term, ...splitCamelCase(term).filter(isAllowedQueryToken)];
  const seen = new Set<string>();
  const deduped: string[] = [];
  for (const variant of variants) {
    const normalized = variant.toLowerCase();
    if (seen.has(normalized)) continue;
    seen.add(normalized);
    deduped.push(variant);
  }
  return deduped;
}

/**
 * Build a safe FTS5 query from natural language input.
 * - Filters stop words
 * - Expands CamelCase terms
 * - Wraps terms in quotes for safety
 * - Uses AND for 1-3 terms, OR for 4+ (BM25 handles multi-match naturally)
 */
export function sanitizeFts5Query(query: string, andThreshold = 3): string {
  const trimmed = query.trim();
  if (!trimmed) return '';

  // Extract user-typed phrase queries
  const phrases: string[] = [];
  const remaining = trimmed.replace(/"([^"]+)"/g, (_match, phrase: string) => {
    const escaped = phrase.replace(/"/g, '""');
    phrases.push(`"${escaped}"`);
    return ' ';
  });

  // Tokenize remaining text
  const terms = remaining
    .split(/[\s:]+/)
    .filter(Boolean)
    .map(term => {
      const escaped = term.replace(/"/g, '""');
      const clean = escaped.replace(/\*$/, '');
      if (!isAllowedQueryToken(clean)) return '';
      const variants = expandQueryTerm(clean);
      if (variants.length === 1) {
        return `"${variants[0]}"`;
      }
      return `(${variants.map(v => `"${v}"`).join(' OR ')})`;
    })
    .filter(Boolean);

  const allTerms = [...phrases, ...terms];
  if (allTerms.length === 0) return '';

  // 1-3 terms: AND for precision. 4+: OR with BM25 ranking.
  if (allTerms.length <= andThreshold) {
    return allTerms.join(' AND ');
  }
  return allTerms.join(' OR ');
}

// ── Cosine Similarity ────────────────────────────────────────

function cosineSimilarity(a: Float32Array, b: Float32Array): number {
  let dot = 0, normA = 0, normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

/** Map cosine [-1,1] to [0,1] */
function normalizedCosine(a: Float32Array, b: Float32Array): number {
  return (cosineSimilarity(a, b) + 1) / 2;
}

// ── Score Blending ───────────────────────────────────────────

/** Blend BM25 and vector scores with configurable alpha */
function blendScores(bm25Score: number, vectorScore: number, alpha: number): number {
  return alpha * vectorScore + (1 - alpha) * bm25Score;
}

/** Exponential recency decay: 1.0 today → 0.37 at 30 days */
function recencyScore(now: number, updatedAt: number): number {
  const ageDays = (now - updatedAt) / 86_400_000;
  return Math.exp(-ageDays / 30);
}

// ── MemorySearch ──────────────────────────────────────────────

export class MemorySearch {
  private db: DatabaseManager;
  private embeddings: EmbeddingManager;
  private readonly namespace: string;
  private readonly storageDir: string;
  private readonly config: SearchConfig;
  private initialized = false;
  private lastCleanTime = 0;
  private static readonly CLEAN_INTERVAL_MS = 60_000;

  constructor(namespace?: string, config?: Partial<SearchConfig>) {
    this.namespace = namespace ?? defaultNamespace();
    this.storageDir = getStorageDir(this.namespace);
    this.db = new DatabaseManager(join(this.storageDir, 'memory.db'));
    this.embeddings = new EmbeddingManager();
    this.config = { ...DEFAULT_SEARCH_CONFIG, ...config };
  }

  async init(): Promise<void> {
    if (this.initialized) return;
    // Migrate from older namespace schemes to current --git-common-dir-based
    if (!existsSync(this.storageDir)) {
      const candidates = [showToplevelNamespace(), legacyNamespace()];
      let migrated = false;
      for (const old of candidates) {
        if (!old || old === this.namespace) continue;
        const oldDir = getStorageDir(old);
        if (existsSync(oldDir)) {
          renameSync(oldDir, this.storageDir);
          process.stderr.write(`[SmartMemory] Migrated namespace "${old}" → "${this.namespace}"\n`);
          migrated = true;
          break;
        }
      }
      if (!migrated) {
        mkdirSync(this.storageDir, { recursive: true });
      }
    }
    await this.db.init();
    // Migrate from index.bin if it exists (backfill embeddings into DB)
    this.migrateFromIndexBin();
    // Backfill FTS5 table for existing memories not yet indexed
    this.backfillFts();
    this.initialized = true;
  }

  // ── Store ─────────────────────────────────────────────────

  async store(input: MemoryStoreInput): Promise<{ id: string; action: 'created' | 'updated' }> {
    await this.init();
    this.cleanExpired();

    const ns = input.namespace ?? this.namespace;
    const now = Date.now();
    const expiresAt = input.ttl_hours ? now + input.ttl_hours * 3_600_000 : null;
    const tags = JSON.stringify(input.tags ?? []);
    const metadata = JSON.stringify(input.metadata ?? {});
    const type = input.type ?? 'note';

    // Generate embedding
    const { vec, dims } = await this.embeddings.embed(input.content);
    const embedding = Buffer.from(vec.buffer, vec.byteOffset, vec.byteLength);

    // Check if key already exists in this namespace
    const existing = this.db.get<{ id: string }>(
      'SELECT id FROM memories WHERE key = ? AND namespace = ?',
      [input.key, ns],
    );

    if (existing) {
      this.db.run(
        `UPDATE memories SET
          content = ?, type = ?, tags = ?, embedding = ?, embedding_dims = ?,
          updated_at = ?, expires_at = ?, metadata = ?
         WHERE id = ?`,
        [input.content, type, tags, embedding, dims, now, expiresAt, metadata, existing.id],
      );
      // Sync FTS
      this.db.run('DELETE FROM memories_fts WHERE id = ?', [existing.id]);
      this.db.run('INSERT INTO memories_fts (id, key, content) VALUES (?, ?, ?)',
        [existing.id, input.key, input.content]);
      return { id: existing.id, action: 'updated' };
    } else {
      const id = randomUUID();
      this.db.run(
        `INSERT INTO memories
          (id, key, content, namespace, type, tags, embedding, embedding_dims,
           created_at, updated_at, expires_at, metadata)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
        [id, input.key, input.content, ns, type, tags, embedding, dims,
         now, now, expiresAt, metadata],
      );
      // Sync FTS
      this.db.run('INSERT INTO memories_fts (id, key, content) VALUES (?, ?, ?)',
        [id, input.key, input.content]);
      return { id, action: 'created' };
    }
  }

  // ── Hybrid Search (BM25 + vector) ─────────────────────────

  async search(input: MemorySearchInput): Promise<MemorySearchResult[]> {
    await this.init();
    this.cleanExpired();

    const ns = input.namespace ?? this.namespace;
    const limit = input.limit ?? 10;
    const minSim = input.min_similarity ?? this.config.thresholds.relevance;
    const now = Date.now();

    // Build lookup maps for merging
    const fts5Map = new Map<string, { row: DbRow; score: number }>();
    const vectorMap = new Map<string, { row: DbRow; score: number }>();

    // ── 1. BM25 search via FTS5 ──────────────────────────────
    const ftsQuery = sanitizeFts5Query(input.query, this.config.andQueryTermCount);
    if (ftsQuery) {
      try {
        const { key: keyWeight, content: contentWeight } = this.config.bm25Weights;
        // FTS5 schema: fts5(id UNINDEXED, key, content)
        // bm25() skips UNINDEXED columns, so only 2 weights: key, content
        const ftsRows = this.db.all<{ id: string; rank: number }>(
          `SELECT id, bm25(memories_fts, ${keyWeight}, ${contentWeight}) AS rank
           FROM memories_fts WHERE memories_fts MATCH ?
           ORDER BY rank LIMIT ?`,
          [ftsQuery, limit * 3],
        );

        if (ftsRows.length > 0) {
          const ftsIds = ftsRows.map(r => r.id);
          const ph = ftsIds.map(() => '?').join(', ');
          const rows = this.db.all<DbRow>(
            `SELECT * FROM memories WHERE id IN (${ph}) AND namespace = ? AND (expires_at IS NULL OR expires_at > ?)`,
            [...ftsIds, ns, now],
          );
          const rowMap = new Map(rows.map(r => [r.id, r]));

          for (const fts of ftsRows) {
            const row = rowMap.get(fts.id);
            if (!row) continue;
            // BM25 returns negative values; Math.abs to get positive score
            fts5Map.set(row.id, { row, score: Math.abs(fts.rank) });
          }
        }
      } catch {
        // FTS5 query failed — try LIKE fallback
        this.fts5LikeFallback(input.query, ns, now, limit, fts5Map);
      }
    }

    // ── 2. Vector search (scan DB embeddings) ────────────────
    const { vec: queryVec } = await this.embeddings.embed(input.query);
    const queryDims = queryVec.length;

    const embeddingRows = this.db.all<{ id: string; key: string; embedding: Uint8Array | null; embedding_dims: number; content: string; namespace: string; type: string; tags: string; created_at: number; updated_at: number; expires_at: number | null; metadata: string }>(
      `SELECT * FROM memories WHERE namespace = ? AND embedding IS NOT NULL AND embedding_dims = ? AND (expires_at IS NULL OR expires_at > ?)`,
      [ns, queryDims, now],
    );

    for (const row of embeddingRows) {
      const embedding = row.embedding;
      if (!embedding) continue;
      // node:sqlite returns BLOBs as Uint8Array, not Buffer
      const bytes = embedding instanceof Uint8Array ? embedding : Buffer.from(embedding as ArrayBuffer);
      const vec = new Float32Array(bytes.buffer, bytes.byteOffset, bytes.byteLength / 4);
      if (vec.length !== queryDims) continue;
      const sim = normalizedCosine(queryVec, vec);
      if (sim >= minSim * 0.5) { // use lower threshold for vector; blending may boost
        vectorMap.set(row.id, { row: row as unknown as DbRow, score: sim });
      }
    }

    // ── 3. Merge results (Monsthera-inspired blend) ──────────
    const { blendAlpha, penalties } = this.config;

    // Normalize BM25 scores to [0, 1]
    const maxBm25 = Math.max(...[...fts5Map.values()].map(v => v.score), 1);

    const allIds = new Set([...fts5Map.keys(), ...vectorMap.keys()]);
    const candidates: MemorySearchResult[] = [];

    for (const id of allIds) {
      const fts5Entry = fts5Map.get(id);
      const vectorEntry = vectorMap.get(id);

      const normalizedBm25 = fts5Entry ? fts5Entry.score / maxBm25 : undefined;
      const vectorScore = vectorEntry?.score;
      const row = fts5Entry?.row ?? vectorEntry?.row;
      if (!row) continue;

      let score: number;
      let rawSimilarity: number;

      if (normalizedBm25 !== undefined && vectorScore !== undefined) {
        // Both sources — full blend
        score = blendScores(normalizedBm25, vectorScore, blendAlpha);
        rawSimilarity = vectorScore;
      } else if (normalizedBm25 !== undefined) {
        // FTS5 only — apply penalty
        score = normalizedBm25 * penalties.fts5Only;
        rawSimilarity = 0;
      } else {
        // Vector only — apply penalty
        score = vectorScore! * penalties.vectorOnly;
        rawSimilarity = vectorScore!;
      }

      // Apply recency boost (multiplicative, not additive)
      const recency = recencyScore(now, row.updated_at as number);
      score *= (1 + recency * 0.1);

      if (score >= minSim) {
        candidates.push(rowToResult(row, score, rawSimilarity));
      }
    }

    candidates.sort((a, b) => b.similarity - a.similarity);
    return candidates.slice(0, limit);
  }

  // ── SQL Query ─────────────────────────────────────────────

  async query(input: MemoryQueryInput): Promise<MemorySearchResult[]> {
    await this.init();
    this.cleanExpired();

    const conditions: string[] = ['(expires_at IS NULL OR expires_at > ?)'];
    const params: unknown[] = [Date.now()];

    const ns = input.namespace ?? this.namespace;
    conditions.push('namespace = ?');
    params.push(ns);

    if (input.type) {
      conditions.push('type = ?');
      params.push(input.type);
    }
    if (input.after) {
      conditions.push('created_at >= ?');
      params.push(new Date(input.after).getTime());
    }
    if (input.before) {
      conditions.push('created_at <= ?');
      params.push(new Date(input.before).getTime());
    }
    if (input.tags && input.tags.length > 0) {
      for (const tag of input.tags) {
        const escaped = tag.replace(/\\/g, '\\\\').replace(/%/g, '\\%').replace(/_/g, '\\_');
        conditions.push(`tags LIKE ? ESCAPE '\\'`);
        params.push(`%"${escaped}"%`);
      }
    }

    const limit = input.limit ?? 50;
    const sql = `SELECT * FROM memories WHERE ${conditions.join(' AND ')} ORDER BY updated_at DESC LIMIT ?`;
    params.push(limit);

    const rows = this.db.all<DbRow>(sql, params);
    return rows.map(r => rowToResult(r, 1.0, 1.0));
  }

  // ── Stats ─────────────────────────────────────────────────

  async stats(): Promise<MemoryStats> {
    await this.init();

    const total = (this.db.get<{ n: number }>('SELECT COUNT(*) as n FROM memories') ?? { n: 0 }).n;
    const withEmbedding = (this.db.get<{ n: number }>(
      'SELECT COUNT(*) as n FROM memories WHERE embedding_dims > 0',
    ) ?? { n: 0 }).n;

    const nsRows = this.db.all<{ namespace: string; n: number }>(
      'SELECT namespace, COUNT(*) as n FROM memories GROUP BY namespace',
    );
    const typeRows = this.db.all<{ type: string; n: number }>(
      'SELECT type, COUNT(*) as n FROM memories GROUP BY type',
    );

    return {
      total,
      by_namespace: Object.fromEntries(nsRows.map(r => [r.namespace, r.n])),
      by_type: Object.fromEntries(typeRows.map(r => [r.type, r.n])),
      embedding_coverage: total > 0 ? withEmbedding / total : 0,
    };
  }

  // ── Delete ────────────────────────────────────────────────

  async delete(key: string, namespace?: string): Promise<{ deleted: boolean }> {
    await this.init();
    const ns = namespace ?? this.namespace;
    const existing = this.db.get<{ id: string }>(
      'SELECT id FROM memories WHERE key = ? AND namespace = ?',
      [key, ns],
    );
    if (!existing) return { deleted: false };
    this.db.run('DELETE FROM memories WHERE id = ?', [existing.id]);
    this.db.run('DELETE FROM memories_fts WHERE id = ?', [existing.id]);
    return { deleted: true };
  }

  // ── Compact ──────────────────────────────────────────────

  async compact(namespace?: string): Promise<{
    embedded: number;
    expired_cleaned: number;
    total_after: number;
  }> {
    await this.init();

    // 1. Clean expired memories
    const expiredBefore = this.db.all<{ id: string }>(
      'SELECT id FROM memories WHERE expires_at IS NOT NULL AND expires_at <= ?',
      [Date.now()],
    );
    if (expiredBefore.length > 0) {
      const ph = expiredBefore.map(() => '?').join(', ');
      const ids = expiredBefore.map(e => e.id);
      this.db.run(`DELETE FROM memories WHERE id IN (${ph})`, ids);
      this.db.run(`DELETE FROM memories_fts WHERE id IN (${ph})`, ids);
    }

    // 2. Find memories without embeddings in this namespace
    const ns = namespace ?? this.namespace;
    const noEmbedding = this.db.all<{ id: string; content: string }>(
      'SELECT id, content FROM memories WHERE namespace = ? AND embedding_dims = 0',
      [ns],
    );

    // 3. Generate embeddings for each
    let embedded = 0;
    for (const row of noEmbedding) {
      try {
        const { vec, dims } = await this.embeddings.embed(row.content);
        const buf = Buffer.from(vec.buffer, vec.byteOffset, vec.byteLength);
        this.db.run(
          'UPDATE memories SET embedding = ?, embedding_dims = ? WHERE id = ?',
          [buf, dims, row.id],
        );
        embedded++;
      } catch {
        // Skip failed embeddings — will retry on next compact
      }
    }

    const total = (this.db.get<{ n: number }>('SELECT COUNT(*) as n FROM memories WHERE namespace = ?', [ns]) ?? { n: 0 }).n;

    return {
      embedded,
      expired_cleaned: expiredBefore.length,
      total_after: total,
    };
  }

  // ── Context (token-budgeted) ─────────────────────────────

  async context(input: MemoryContextInput): Promise<MemoryContextResult> {
    await this.init();
    this.cleanExpired();

    const budget = Math.max(500, Math.min(32000, input.budget_tokens ?? 4000));
    const hint = input.hint?.trim().slice(0, 500) || undefined;
    const ns = input.namespace ?? this.namespace;
    const estimateTokens = (text: string) => Math.ceil(text.length / 4);

    const includedIds = new Set<string>();
    const sections: Array<{ key: string; type: string; content: string }> = [];
    let usedTokens = 0;

    // Helper: add a memory if it fits the budget
    const tryAdd = (id: string, key: string, type: string, content: string): boolean => {
      if (includedIds.has(id)) return false;
      // Estimate tokens for this entry: "### key\n*type*\ncontent\n\n"
      const entry = `### ${key}\n*${type}*\n${content}\n`;
      const entryTokens = estimateTokens(entry);
      if (usedTokens + entryTokens > budget) {
        // Try truncating content to fit remaining budget
        const remainingTokens = budget - usedTokens;
        const headerTokens = estimateTokens(`### ${key}\n*${type}*\n`);
        const availableContentTokens = remainingTokens - headerTokens - 2; // 2 for newlines
        if (availableContentTokens < 20) return false; // not worth truncating
        const truncatedContent = content.slice(0, availableContentTokens * 4);
        const truncatedEntry = `### ${key}\n*${type}*\n${truncatedContent}…\n`;
        sections.push({ key, type, content: truncatedContent + '…' });
        usedTokens += estimateTokens(truncatedEntry);
        includedIds.add(id);
        return true;
      }
      sections.push({ key, type, content });
      usedTokens += entryTokens;
      includedIds.add(id);
      return true;
    };

    // 1. If hint provided: hybrid search for relevant memories
    if (hint) {
      const hintResults = await this.search({
        query: hint,
        namespace: ns,
        limit: 20,
        min_similarity: 0.4,
      });
      for (const r of hintResults) {
        if (usedTokens >= budget) break;
        tryAdd(r.id, r.key, r.type, r.content);
      }
    }

    // 2. Always include recent decisions & solutions
    for (const type of ['decision', 'solution']) {
      const results = await this.query({ type, namespace: ns, limit: 10 });
      for (const r of results) {
        if (usedTokens >= budget) break;
        tryAdd(r.id, r.key, r.type, r.content);
      }
    }

    // 3. Fill remaining budget with context & patterns
    for (const type of ['context', 'pattern']) {
      const results = await this.query({ type, namespace: ns, limit: 10 });
      for (const r of results) {
        if (usedTokens >= budget) break;
        tryAdd(r.id, r.key, r.type, r.content);
      }
    }

    // Build output markdown
    const contextStr = sections.map(s => `### ${s.key}\n*${s.type}*\n${s.content}`).join('\n\n');

    return {
      context: contextStr,
      memories_included: sections.length,
      tokens_used: usedTokens,
    };
  }

  // ── Snapshot (save/load session state) ─────────────────────

  async snapshot(input: MemorySnapshotInput): Promise<MemorySnapshotResult> {
    await this.init();

    const ns = input.namespace ?? this.namespace;

    if (input.action === 'save') {
      const summary = (input.summary ?? '').trim().slice(0, 1000);
      if (!summary) throw new Error('summary is required for snapshot save');

      // Validate and sanitize pending items
      let pending: string[] = [];
      if (Array.isArray(input.pending)) {
        pending = input.pending
          .slice(0, 20)
          .map(item => String(item).trim().slice(0, 200))
          .filter(item => item.length > 0);
      }

      // Build content
      const contentLines = ['## Session State', '', '### Working On', summary];
      if (pending.length > 0) {
        contentLines.push('', '### Pending');
        for (const item of pending) {
          contentLines.push(`- ${item}`);
        }
      }
      const content = contentLines.join('\n');

      await this.store({
        key: 'session-snapshot',
        content,
        namespace: ns,
        type: 'snapshot',
        tags: ['session', 'snapshot'],
      });

      return { saved: true, key: 'session-snapshot' };
    }

    if (input.action === 'load') {
      const row = this.db.get<{ content: string; updated_at: number }>(
        'SELECT content, updated_at FROM memories WHERE key = ? AND namespace = ? AND (expires_at IS NULL OR expires_at > ?)',
        ['session-snapshot', ns, Date.now()],
      );

      if (!row) return { empty: true };

      // Parse content back to structured form
      const content = row.content;
      let summary = '';
      const pending: string[] = [];

      const workingOnMatch = content.match(/### Working On\n([\s\S]*?)(?=\n### |\n## |$)/);
      if (workingOnMatch) {
        summary = workingOnMatch[1].trim();
      }

      const pendingMatch = content.match(/### Pending\n([\s\S]*?)(?=\n### |\n## |$)/);
      if (pendingMatch) {
        const lines = pendingMatch[1].trim().split('\n');
        for (const line of lines) {
          const item = line.replace(/^- /, '').trim();
          if (item) pending.push(item);
        }
      }

      return { summary, pending, saved_at: row.updated_at };
    }

    throw new Error(`Invalid action: "${input.action}". Must be "save" or "load".`);
  }

  close(): void {
    this.db.close();
  }

  // ── Internals ─────────────────────────────────────────────

  /** Migrate vectors from legacy index.bin into DB embedding columns */
  private migrateFromIndexBin(): void {
    const indexBinPath = join(this.storageDir, 'index.bin');
    if (!existsSync(indexBinPath)) return;

    try {
      const legacyIndex = new VectorIndex();
      legacyIndex.loadFrom(indexBinPath);

      if (legacyIndex.size === 0) {
        unlinkSync(indexBinPath);
        return;
      }

      // For each vector in index.bin, update the DB row if it has no embedding
      let migrated = 0;
      const allMemories = this.db.all<{ id: string; embedding_dims: number }>(
        'SELECT id, embedding_dims FROM memories',
      );

      for (const mem of allMemories) {
        if (mem.embedding_dims > 0) continue; // already has embedding in DB
        // Try to get vector from legacy index — use internal search to verify it exists
        // VectorIndex doesn't expose get(), so we check via has()
        if (!legacyIndex.has(mem.id)) continue;

        // Extract the vector by doing a search with itself
        // This is a workaround since VectorIndex doesn't have a get() method
        // We'll just skip migration for entries we can't extract
        // The compact() command will re-generate these embeddings anyway
      }

      // Remove the index.bin file — compact() will regenerate any missing embeddings
      unlinkSync(indexBinPath);
      process.stderr.write(`[SmartMemory] Removed legacy index.bin (embeddings stored in DB)\n`);
    } catch {
      // Non-fatal: index.bin may be corrupted
      try { unlinkSync(indexBinPath); } catch { /* ignore */ }
    }
  }

  /** One-time backfill: sync memories into FTS5 table if missing */
  private backfillFts(): void {
    try {
      const ftsCount = (this.db.get<{ n: number }>('SELECT COUNT(*) as n FROM memories_fts') ?? { n: 0 }).n;
      const memCount = (this.db.get<{ n: number }>('SELECT COUNT(*) as n FROM memories') ?? { n: 0 }).n;
      if (ftsCount >= memCount) return;

      this.db.run(
        `INSERT INTO memories_fts (id, key, content)
         SELECT id, key, content FROM memories
         WHERE id NOT IN (SELECT id FROM memories_fts)`
      );
    } catch {
      // FTS5 not available or migration pending — skip silently
    }
  }

  /** Clean expired memories — debounced to run at most once per 60s */
  private cleanExpired(): void {
    const now = Date.now();
    if (now - this.lastCleanTime < MemorySearch.CLEAN_INTERVAL_MS) return;
    this.lastCleanTime = now;

    const expired = this.db.all<{ id: string }>(
      'SELECT id FROM memories WHERE expires_at IS NOT NULL AND expires_at <= ?',
      [now],
    );
    if (expired.length === 0) return;

    const expiredIds = expired.map(e => e.id);
    const ph = expiredIds.map(() => '?').join(', ');
    this.db.run(`DELETE FROM memories WHERE id IN (${ph})`, expiredIds);
    this.db.run(`DELETE FROM memories_fts WHERE id IN (${ph})`, expiredIds);
  }

  /** LIKE-based fallback when FTS5 query parsing fails */
  private fts5LikeFallback(
    query: string, ns: string, now: number, limit: number,
    fts5Map: Map<string, { row: DbRow; score: number }>,
  ): void {
    const keywords = query
      .split(/\s+/)
      .map(w => w.replace(/[^\w.-]/g, ''))
      .filter(w => w.length >= 3);

    if (keywords.length === 0) return;

    const likeClauses = keywords.map(() => '(content LIKE ? OR key LIKE ?)');
    const likeParams: unknown[] = [];
    for (const kw of keywords) {
      likeParams.push(`%${kw}%`, `%${kw}%`);
    }

    const rows = this.db.all<DbRow>(
      `SELECT * FROM memories WHERE namespace = ? AND (expires_at IS NULL OR expires_at > ?)
       AND (${likeClauses.join(' OR ')})
       ORDER BY updated_at DESC LIMIT ?`,
      [ns, now, ...likeParams, limit * 2],
    );

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      fts5Map.set(row.id, { row, score: 1 / (i + 1) }); // reciprocal rank
    }
  }
}

// ── DB row shape (raw from node:sqlite) ──────────────────────

interface DbRow {
  [key: string]: unknown;
  id: string;
  key: string;
  content: string;
  namespace: string;
  type: string;
  tags: string;
  embedding_dims: number;
  created_at: number;
  updated_at: number;
  expires_at: number | null;
  metadata: string;
}

function rowToResult(row: DbRow, similarity: number, rawSimilarity: number): MemorySearchResult {
  return {
    id: row.id,
    key: row.key,
    content: row.content,
    namespace: row.namespace,
    type: row.type,
    tags: JSON.parse(row.tags) as string[],
    similarity,
    raw_similarity: rawSimilarity,
    created_at: row.created_at,
    updated_at: row.updated_at,
  };
}
