/**
 * Smart Memory — Shared AGENT-MEMORY-CONTEXT.md export + namespace helpers.
 * Used by both session-start and post-tool hooks.
 */

import { createHash } from 'crypto';
import { execFileSync } from 'child_process';
import { basename, resolve, dirname, join } from 'path';
import { writeFileSync } from 'fs';

// ── Namespace helpers (must match server/src/index.ts) ───────

export function getProjectRoot() {
  try {
    const gitCommonDir = execFileSync('git', ['rev-parse', '--git-common-dir'], {
      encoding: 'utf-8', stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    return dirname(resolve(gitCommonDir));
  } catch {
    return process.cwd();
  }
}

export function getNamespace() {
  const root = getProjectRoot();
  const name = basename(root) || 'default';
  const hash = createHash('sha256').update(root).digest('hex').slice(0, 8);
  return name + '-' + hash;
}

// ── Export configuration with per-type limits ────────────────

const EXPORT_TYPES = [
  { type: 'decision', label: 'Architecture Decisions', limit: 20 },
  { type: 'solution', label: 'Solutions & Fixes',      limit: 20 },
  { type: 'context',  label: 'Project Context',        limit: 10 },
  { type: 'pattern',  label: 'Recurring Patterns',     limit: 10 },
];

/**
 * Export valuable memories to AGENT-MEMORY-CONTEXT.md at the project root.
 * @param {object} db   Open DatabaseSync instance (read access sufficient)
 * @param {string} namespace  Project namespace
 * @param {number} now  Current timestamp (Date.now())
 */
export function exportContextMd(db, namespace, now) {
  const projectRoot = getProjectRoot();
  const projectName = basename(projectRoot);
  const contextPath = join(projectRoot, 'AGENT-MEMORY-CONTEXT.md');

  // Query each type with its own LIMIT (prevents unbounded growth)
  const valuable = [];
  for (const section of EXPORT_TYPES) {
    const rows = db.prepare(
      'SELECT key, content, type, tags, updated_at FROM memories ' +
      'WHERE namespace = ? AND type = ? ' +
      'AND (expires_at IS NULL OR expires_at > ?) ' +
      'ORDER BY updated_at DESC LIMIT ?'
    ).all(namespace, section.type, now, section.limit);
    valuable.push(...rows);
  }

  if (valuable.length === 0) return;

  const statsRow = db.prepare(
    'SELECT COUNT(*) as total FROM memories WHERE namespace = ? AND (expires_at IS NULL OR expires_at > ?)'
  ).get(namespace, now);

  const mdLines = [];
  const date = new Date().toLocaleDateString();

  mdLines.push('# ' + projectName + ' — Project Context');
  mdLines.push('\n> Auto-generated by Smart Memory on ' + date + '.');
  mdLines.push('> Namespace: `' + namespace + '` | Total memories: ' + Number(statsRow?.total ?? 0));
  mdLines.push('> This file is for agents (Codex, Gemini, etc.) that don\'t have MCP access.\n');

  for (const section of EXPORT_TYPES) {
    const rows = valuable.filter(r => r.type === section.type);
    if (rows.length === 0) continue;

    mdLines.push('## ' + section.label + '\n');
    for (const row of rows) {
      const content = String(row.content ?? '');
      const tags = row.tags ? JSON.parse(String(row.tags)) : [];
      const tagStr = tags.length > 0 ? ' `' + tags.join('` `') + '`' : '';
      const updated = new Date(Number(row.updated_at)).toLocaleDateString();
      mdLines.push('### ' + row.key);
      mdLines.push('*' + updated + '*' + tagStr + '\n');
      mdLines.push(content);
      mdLines.push('');
    }
  }

  try {
    writeFileSync(contextPath, mdLines.join('\n') + '\n', 'utf-8');
  } catch {
    // Non-critical — don't fail the hook if write fails
  }
}
